module.exports={
  itemsPostes: [{id: 'Voiturier', name: 'Voiturier'}, 
                {id: 'Serveur', name: 'Serveur'}, 
                {id: 'Garçon de café', name: 'Garçon de café'}, 
                {id: 'Plongeur',name: 'Plongeur'},
                {id: 'Runner', name: 'Runner'}, 
                {id: 'Sommelier',name: 'Sommelier'},
                {id: 'Chef de rang', name: 'Chef de rang'},
                {id: "Maître d'hôtel", name: "Maître d'hôtel"},
                {id: 'Manager', name: 'Manager'}, 
                {id: 'Chef de cuisine',name: 'Chef de cuisine'},
                {id: 'Chef de partie',name: 'Chef de partie'},
                {id: 'Commis de cuisine', name: 'Commis de cuisine'}, 
                {id: 'Pizzaiolo',name: 'Pizzaiolo'},
                {id: 'Pâtissier',name: 'Pâtissier'},
],
itemsLangues: [{id: 'Français', name: 'Français'}, 
                {id: 'Anglais', name: 'Anglais'}, 
                {id: 'Espagnol', name: 'Espagnol'}, 
                {id: 'Italien',name: 'Italien'},
                {id: 'Allemand', name: 'Allemand'}, 
                {id: 'Chinois',name: 'Chinois'},
],
itemsContrats: [{id: 'CDI', name: 'CDI'}, 
                {id: 'CDD', name: 'CDD'}, 
                {id: 'Extra', name: 'Extra'}, 
]
}